// Even Fibonacci Sequence
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var previousNumber = 2;
var currentNumber = 1;
var total = 0;

var nextNumber;

function fibonacci() {
    if (total += (previousNumber % 2  === 0) || (total += (currentNumber % 2 === 0))) {
        
    }
    for (let i = 0; i < 500; i++) {
        nextNumber = currentNumber + previousNumber;
        previousNumber = currentNumber;
        currentNumber = nextNumber;
        if (currentNumber % 2 === 0 && currentNumber <= 4000000) {
            total += currentNumber;
            
        }
    }
    return console.log(total);
}
fibonacci();

